# Generated by Django 2.0.3 on 2018-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameENG', models.CharField(max_length=500)),
                ('nameSLO', models.CharField(max_length=500)),
                ('procedure_id', models.CharField(max_length=10)),
            ],
        ),
    ]
