# Generated by Django 2.0.3 on 2018-06-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfchatbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='lemma',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
